apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    name: webapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: webapp-pod
  template:
    metadata:
      name: webapp-pod
      labels:
        name: webapp-pod
    spec:
      containers:
        - name: webapp
          image: webapp
          ports:
            - containerPort: 9000
          imagePullPolicy: Never

