apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    name: webapp-service
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30001
  selector:
    name: webapp-pod
