apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    name: webapp-pod
spec:
  containers:
    - name: webapp
      image: webapp
      ports:
        - containerPort: 9000
      imagePullPolicy: Never
